services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - /home/server/server-share/dockerfiles/mealie/data/:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: true
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.schultzserver.ca
    labels:
      - traefik.enable=true
      - traefik.http.routers.mealie.rule=Host(`mealie.schultzserver.ca`)
      - traefik.http.routers.mealie.entrypoints=https
      - traefik.http.routers.mealie.tls=true
      - traefik.http.routers.mealie.tls.certresolver=cloudflare
      - traefik.http.services.mealie.loadbalancer.server.port=9000
    networks:
      - frontbridge
networks:
  frontbridge:
    external: true
