services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=http://jellyfin.schultzserver.ca #optional
    volumes:
      - /home/server/server-share/dockerfiles/jellyfin/config:/config
      - /home/server/server-share/dockerfiles/jellyfin/cache:/cache
      - /home/server/server-share/mediafiles/shows:/shows
      - /home/server/server-share/mediafiles/movies:/movies
      - /home/server/server-share/mediafiles/anime:/anime
      - /home/server/server-share/mediafiles/homemovies:/homemovies
      # ports:
      # - 8096:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    networks:
      - frontbridge
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.schultzserver.ca`)
      - traefik.http.routers.jellyfin.entrypoints=https
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.tls.certresolver=cloudflare
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM} #optional
    volumes:
      - /home/server/server-share/dockerfiles/plex/config:/config
      - /home/server/server-share/dockerfiles/plex/transcode:/transcode
      - /home/server/server-share/mediafiles/shows:/shows
      - /home/server/server-share/mediafiles/movies:/movies
      - /home/server/server-share/mediafiles/anime:/anime
      - /home/server/server-share/mediafiles/homemovies:/homemovies
    networks:
      - frontbridge
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.schultzserver.ca`)
      - traefik.http.routers.plex.entrypoints=https
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.tls.certresolver=cloudflare
      - traefik.http.services.plex.loadbalancer.server.port=32400
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/server/server-share/dockerfiles/jellyseerr/config:/app/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.schultzserver.ca`)
      - traefik.http.routers.jellyseerr.entrypoints=https
      - traefik.http.routers.jellyseerr.tls=true
      - traefik.http.routers.jellyseerr.tls.certresolver=cloudflare
      - traefik.http.services.jellyseerr.loadbalancer.server.port=5055
      - traefik.docker.network=frontbridge
    networks:
      - frontbridge
      - gluetun
networks:
  frontbridge:
    external: true
  gluetun:
    external: true
