name: containermanagement
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock --log-level DEBUG
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERFOLDER}/portainer/data:/data
    ports:
      - 9443:9443
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.tls: true
      traefik.http.routers.portainer.rule: Host('portainer.${URL}')
      traefik.http.services.portainer.loadbalancer.server.port: 9000
      glance.name: Portainer
      glance.icon: di:portainer
      glance.url: https://portainer.${URL}
      glance.category: management
      glance.id: Portainer
    networks:
      - frontbridge
  dockerproxy:
    container_name: dockerproxy
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    restart: always
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    labels:
      glance.name: Docker Proxy
      glance.icon: di:docker
      glance.category: management
      glance.parent: Portainer 
    networks:
      - backbridge
networks:
  frontbridge:
    external: true
  backbridge:
    external: true
